FROM php:8.1.9-alpine

RUN apk add --no-cache $PHPIZE_DEPS \
    && pecl install xdebug \
    && docker-php-ext-enable xdebug

COPY --from=composer:2.3.10 /usr/bin/composer /usr/local/bin/composer

COPY . /toastie
COPY ./conf.d/xdebug.ini /usr/local/etc/php/conf.d/error_reporting.ini
COPY ./conf.d/error_reporting.ini /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

WORKDIR /toastie
